baseURL = 'https://kabuqin.github.io/cappuccino.github.io/'
languageCode = 'zh-cn'
title = '卡布奇诺的技术笔记'
theme = 'PaperMod'

[params]
    env = "production"
    title = "卡布奇诺的技术笔记"
    description = "关于OSCP、内网渗透与生活的碎片"
    author = { name = "卡布奇诺" }
    # 自动根据 Git 提交时间识别日期
    enableGitInfo = true

[menu]
    [[menu.main]]
        name = "首页"
        url = "/"
        weight = 10
    [[menu.main]]
        name = "文章"
        url = "posts"
        weight = 20